### ISSUE TITLE
Non-owners cannot join voicechat when it gets created

### ISSUE THREAD

**Issue by dimapanfilov** [Yes-Theory-Fam/yesbot-ts#208] opened 2021-03-04 17:08 UTC
After owner joins, the VC stays locked. If the owner leaves and rejoins then that fixes the issue

Frequency: More often lately 

Maybe more discord inconsistency 🤔 ?

**Comment by geisterfurz007** [comment] 2021-03-04 17:39
Something that might cause the issue is a race condition between bot and user.  
If the owner joins before the database entry is saved, the voice state handler will just return because no matching room was found. That would also explain why it worked when the owner leaves and rejoins because then the database entry exists and the bot functions as expected.

This can be checked by spam clicking on the room as it's being created to be faster than the bot and trying to get in before the message "Your room [...] was created." is sent. In that case the room is likely to not get unlocked.

If that's the case, the fix is surprisingly straightforward: Move creation of the database entry further up; ideally between creation of the channel and setting the permissions that allow the owner to join. That way the owner will only be able to join once the entity is saved to the db.

**Comment by geisterfurz007** [comment] 2021-06-04 13:47
This rarely happens in general and hasn't happened since a month so I am closing this, hoping the issue is indeed fixed in https://github.com/Yes-Theory-Fam/yesbot-ts/commit/d05278360ba05eed7a4097ad85063cac2f550813

**Closed by geisterfurz007** 2021-06-04 13:47 UTC
Labels: bug, needs infos, needs investigation
