### ISSUE TITLE
storing birthday in DB even after a user leaves and rejoins the server

### ISSUE THREAD

**Issue by findtravishere** [Yes-Theory-Fam/yesbot-ts#185] opened 2020-11-24 05:07 UTC
maybe an issue for the backend(?) but groups are stored in the DB even after a user leaves but birthdays are reset back to unknown.

**Comment by geisterfurz007** [comment] 2020-11-24 08:07
Yeah, this is indeed faulty but duplicate of #37

**Closed by geisterfurz007** 2020-11-24 08:07 UTC
Labels: enhancement

**Comment by findtravishere** [comment] 2020-11-24 08:38
right 🤔 i knew i saw it somewhere before, mb
